import React from "react";
import { BookOpen, Coffee, Moon, Zap, Shield, Lightbulb, Target, Headphones } from "lucide-react-native";

export const STORYLINES = {
  deepWork: {
    name: "Deep Work",
    description: "Immersive soundscapes for intense focus sessions",
    gradient: ["#667eea", "#764ba2"] as const,
    icon: <Target color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    duration: "2-4 hours",
    category: "productivity",
  },
  readPower: {
    name: "Read Power",
    description: "Enhance comprehension and retention while reading",
    gradient: ["#f093fb", "#f5576c"] as const,
    icon: <BookOpen color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    duration: "30-90 min",
    category: "learning",
  },
  powerNap: {
    name: "Power Nap",
    description: "Quick rejuvenation for optimal rest",
    gradient: ["#4facfe", "#00f2fe"] as const,
    icon: <Moon color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    duration: "15-30 min",
    category: "rest",
  },
  stressCreate: {
    name: "Stress Create",
    description: "Transform stress into creative energy",
    gradient: ["#fa709a", "#fee140"] as const,
    icon: <Lightbulb color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    duration: "45-90 min",
    category: "creativity",
  },
  morningBoost: {
    name: "Morning Boost",
    description: "Energizing start to your day",
    gradient: ["#30cfd0", "#330867"] as const,
    icon: <Coffee color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    duration: "20-45 min",
    category: "energy",
  },
  anxietyShield: {
    name: "Anxiety Shield",
    description: "Protective soundscape for anxious moments",
    gradient: ["#a8edea", "#fed6e3"] as const,
    icon: <Shield color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    duration: "15-60 min",
    category: "wellness",
  },
  activeListening: {
    name: "Active Listening",
    description: "Enhanced focus for meetings and conversations",
    gradient: ["#667eea", "#764ba2"] as const,
    icon: <Headphones color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    duration: "30-120 min",
    category: "communication",
  },
  energyRecharge: {
    name: "Energy Recharge",
    description: "Quick mental and physical energy restoration",
    gradient: ["#fa709a", "#fee140"] as const,
    icon: <Zap color="#fff" size={28} />,
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    duration: "10-30 min",
    category: "energy",
  },
};