#!/bin/bash

# Audio File Download Script for ADHD Focus Music App
# This script downloads free audio samples for the app
# Uses freesound.org API-free downloads and generates simple tones

set -e

AUDIO_DIR="./assets/audio"

echo "🎵 ADHD Focus Music App - Audio File Setup"
echo "=========================================="
echo ""

# Create directories
echo "📁 Creating audio directories..."
mkdir -p "$AUDIO_DIR/noise"
mkdir -p "$AUDIO_DIR/pad"
mkdir -p "$AUDIO_DIR/pulse"
mkdir -p "$AUDIO_DIR/binaural"

echo "✅ Directories created"
echo ""

echo "⚠️  AUDIO FILE GENERATION REQUIRED"
echo "=========================================="
echo ""
echo "This app requires audio files to function. You have two options:"
echo ""
echo "Option 1: Generate with Audacity (Recommended)"
echo "---------------------------------------------"
echo "1. Install Audacity (https://www.audacityteam.org/)"
echo "2. Follow the instructions in assets/audio/README.md"
echo "3. Generate all required files"
echo ""
echo "Option 2: Use Placeholder Files (For Testing)"
echo "---------------------------------------------"
echo "Use ffmpeg to generate simple placeholder tones:"
echo ""
echo "# White Noise (5 seconds)"
echo "ffmpeg -f lavfi -i anoisesrc=duration=5:color=white:sample_rate=44100 -acodec libmp3lame assets/audio/noise/white-noise.mp3"
echo ""
echo "# Pink Noise (5 seconds)"
echo "ffmpeg -f lavfi -i anoisesrc=duration=5:color=pink:sample_rate=44100 -acodec libmp3lame assets/audio/noise/pink-noise.mp3"
echo ""
echo "# Brown Noise (5 seconds)"
echo "ffmpeg -f lavfi -i anoisesrc=duration=5:color=brown:sample_rate=44100 -acodec libmp3lame assets/audio/noise/brown-noise.mp3"
echo ""
echo "# Deep Pad (110 Hz sine wave, 5 seconds)"
echo "ffmpeg -f lavfi -i \"sine=frequency=110:duration=5\" -acodec libmp3lame assets/audio/pad/deep-pad-110hz.mp3"
echo ""
echo "# Mid Pad (220 Hz sine wave, 5 seconds)"
echo "ffmpeg -f lavfi -i \"sine=frequency=220:duration=5\" -acodec libmp3lame assets/audio/pad/mid-pad-220hz.mp3"
echo ""
echo "# High Pad (440 Hz sine wave, 5 seconds)"
echo "ffmpeg -f lavfi -i \"sine=frequency=440:duration=5\" -acodec libmp3lame assets/audio/pad/high-pad-440hz.mp3"
echo ""
echo "# Pulse (60 BPM, 5 seconds)"
echo "ffmpeg -f lavfi -i \"sine=frequency=1:duration=5\" -acodec libmp3lame assets/audio/pulse/pulse-60bpm.mp3"
echo ""
echo "# Pulse (80 BPM, 5 seconds)"
echo "ffmpeg -f lavfi -i \"sine=frequency=1.33:duration=5\" -acodec libmp3lame assets/audio/pulse/pulse-80bpm.mp3"
echo ""
echo "# Binaural Beats - Left Channel (200 Hz)"
echo "ffmpeg -f lavfi -i \"sine=frequency=200:duration=5\" -acodec libmp3lame assets/audio/binaural/binaural-40hz-left.mp3"
echo ""
echo "# Binaural Beats - Right Channel (240 Hz)"
echo "ffmpeg -f lavfi -i \"sine=frequency=240:duration=5\" -acodec libmp3lame assets/audio/binaural/binaural-40hz-right.mp3"
echo ""
echo "Option 3: Use Free Sound Libraries"
echo "---------------------------------------------"
echo "Download from freesound.org (requires free account):"
echo "- Search for 'white noise loopable'"
echo "- Search for 'ambient pad loopable'"
echo "- Search for 'binaural beats'"
echo ""
echo "=========================================="
echo ""
echo "⚠️  The app will NOT produce sound until these files are added!"
echo ""
